export interface Artist {
  id: string;
  name: string;
  role: string;
  type: string;
  image: ImageQuality[];
  url: string;
}

export interface ArtistInfo {
  id: number;
  name: string;
  link: string;
  picture: string;
  picture_small: string;
  picture_medium: string;
  picture_big: string;
  picture_xl: string;
  nb_album: number;
  nb_fan: number;
  genres?: string[];
}

export interface ImageQuality {
  quality: string;
  url: string;
}

export interface DownloadUrl {
  quality: string;
  url: string;
}

export interface Song {
  id: string;
  name: string;
  type: string;
  year: string;
  releaseDate: string | null;
  duration: number;
  label: string;
  explicitContent: boolean;
  playCount: number;
  language: string;
  hasLyrics: boolean;
  lyricsId: string | null;
  url: string;
  copyright: string;
  album: { id: string; name: string; url: string };
  artists: {
    primary: Artist[];
    featured: Artist[];
    all: Artist[];
  };
  image: ImageQuality[];
  downloadUrl: DownloadUrl[];
  audioUrl?: string;        // Resolved YouTube audio URL (set lazily on play)
  spotifyId?: string;       // Spotify track ID for reference
  preview?: string;         // 30s preview URL (Spotify or iTunes)
  youtubeId?: string;       // Resolved YouTube video ID
  isRadio?: boolean;        // True if this is a radio stream
  radioStreamUrl?: string;  // Direct stream URL for radio
  radioMeta?: {             // Live metadata from icecast stream
    title: string;          // e.g. "Artist - Song Title"
    station: string;        // Station name
  };
  genre?: string;           // Primary genre (e.g. "Pop", "Rock") — from iTunes primaryGenreName
  isAutoplay?: boolean;     // True if this track was generated by the Autoplay/Infinity system
  uniqueId?: string;        // Unique identifier for rendering lists with duplicate tracks
}

/** Shape returned by radio-browser.info */
export interface RadioStation {
  stationuuid: string;
  name: string;
  url: string;
  url_resolved: string;
  homepage: string;
  favicon: string;
  tags: string;
  country: string;
  countrycode: string;
  state: string;
  language: string;
  languagecodes: string;
  codec: string;
  bitrate: number;
  votes: number;
  clickcount: number;
  clicktrend: number;
  lastchangetime: string;
  lastcheckok: number;      // 1 = online, 0 = offline
  geo_lat: number | null;
  geo_long: number | null;
}

export interface Album {
  id: string;
  name: string;
  description: string;
  year: string;
  type: string;
  playCount: number;
  language: string;
  explicitContent: boolean;
  songCount: number;
  url: string;
  primaryArtists: Artist[];
  featuredArtists: Artist[];
  artists: Artist[];
  image: ImageQuality[];
  songs: Song[];
}

export interface HomeFeed {
  trending: {
    songs: Song[];
    albums: Album[];
  };
  albums: Album[];
  charts: any[];
  playlists: any[];
}
