import { Request, Response } from 'express';


type YoutubeApiError = {
  error?: {
    message?: string;
    errors?: Array<{ reason?: string }>;
  };
};

const QUOTA_ERROR_REASONS = new Set([
  'quotaExceeded',
  'dailyLimitExceeded',
  'rateLimitExceeded',
  'userRateLimitExceeded',
]);

const KEY_EXHAUST_COOLDOWN_MS = 60 * 60 * 1000;

let activeKeyIndex = 0;

const exhaustedKeyUntil: Record<number, number> = {};

const HARD_EXCLUDED_TERMS = [
  'official music video',
  'music video',
  ' mv ',
  '(mv)',
  '[mv]',
  '#shorts',
];

const SOFT_EXCLUDED_TERMS = [
  'official video',
  'video klip',
  'lyric video',
  'live',
  'concert',
  'performance',
  'reaction',
  'teaser',
  'trailer',
  'karaoke',
  'cover',
];

const PREFERRED_TERMS = ['official audio', 'audio', 'topic', 'provided to youtube by', 'auto-generated by youtube'];

function normalizeText(text: string) {
  return ` ${text.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim()} `;
}

function sanitizeTitle(text: string) {
  return normalizeText(text)
    .replace(/\b(official|music|video|mv|lyric|live|performance|audio|visualizer|karaoke)\b/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function isTopicChannel(channelTitle: string) {
  const normalized = normalizeText(channelTitle).trim();
  return normalized.endsWith(' topic') || normalized.includes(' - topic');
}

function getYoutubeApiKeys() {
  const keys = [
    process.env.YOUTUBE_API_KEY1,
    process.env.YOUTUBE_API_KEY2,
    process.env.YOUTUBE_API_KEY3,
    process.env.YOUTUBE_API_KEY, // backward compatibility
  ].filter((value, index, arr): value is string => Boolean(value) && arr.indexOf(value) === index);

  return keys;
}

function isQuotaError(status: number, payload: YoutubeApiError) {
  if (status !== 403 && status !== 429) return false;

  const reasons = payload.error?.errors?.map((entry) => entry.reason).filter(Boolean) ?? [];
  if (reasons.length === 0) return true;

  return reasons.some((reason) => QUOTA_ERROR_REASONS.has(reason as string));
}

function getSearchUrl(searchQuery: string, apiKey: string) {
  return `https://www.googleapis.com/youtube/v3/search?part=id,snippet&maxResults=12&q=${encodeURIComponent(searchQuery)}&type=video&videoCategoryId=10&key=${apiKey}`;
}

function scoreCandidate(item: any, expectedTitle: string, expectedArtist: string) {
  const title = item?.snippet?.title ?? '';
  const description = item?.snippet?.description ?? '';
  const channelTitle = item?.snippet?.channelTitle ?? '';
  const text = normalizeText(`${title} ${description} ${channelTitle}`);
  const expectedTitleNormalized = sanitizeTitle(expectedTitle);
  const candidateTitleNormalized = sanitizeTitle(title);
  const expectedArtistNormalized = normalizeText(expectedArtist).trim();
  const topic = isTopicChannel(channelTitle);

  // Exclude hard music-video indicators
  if (HARD_EXCLUDED_TERMS.some((term) => text.includes(` ${normalizeText(term).trim()} `))) return -999;

  let score = 0;

  // Prefer direct audio uploads / topic channels
  PREFERRED_TERMS.forEach((term) => {
    if (text.includes(` ${normalizeText(term).trim()} `)) score += 6;
  });
  if (topic) score += 120;

  // Down-rank non-direct song formats
  SOFT_EXCLUDED_TERMS.forEach((term) => {
    if (text.includes(` ${normalizeText(term).trim()} `)) score -= 8;
  });

  // Prioritize clean title match (usually Topic upload title is plain).
  if (expectedTitleNormalized && candidateTitleNormalized === expectedTitleNormalized) score += 80;
  else if (expectedTitleNormalized && candidateTitleNormalized.startsWith(expectedTitleNormalized)) score += 40;

  // Keep artist relevance strong.
  if (expectedArtistNormalized && text.includes(` ${expectedArtistNormalized} `)) score += 20;

  // Slightly prefer shorter direct-song uploads over long intros.
  const duration = item?.contentDetails?.duration as string | undefined;
  if (duration) {
    const isLongForm = /PT(\d+H|\d{2,}M)/.test(duration);
    if (isLongForm) score -= 3;
  }

  return score;
}

export const getSearchYoutube = async (req: Request, res: Response) => {
  const query = req.query.query as string || '';
  const title = req.query.title as string || '';
  const artist = req.query.artist as string || '';

  const apiKeys = getYoutubeApiKeys();

  if (apiKeys.length === 0) {
    console.error('YouTube API keys are missing');
    return res.status(500).json({ error: 'Server configuration error' });
  }

  try {
    const searchQuery = query?.trim() || `${title} ${artist} topic`.trim();
    if (!searchQuery) return res.status(400).json({ error: 'Missing query parameters' });

    const now = Date.now();
    let firstErrorStatus = 500;
    let searchData: any = null;

    for (let i = activeKeyIndex; i < apiKeys.length; i++) {
      const exhaustedUntil = exhaustedKeyUntil[i] ?? 0;
      if (now < exhaustedUntil) continue;

      const key = apiKeys[i];
      const fetchRes = await fetch(getSearchUrl(searchQuery, key));
      const data = (await fetchRes.json()) as YoutubeApiError & { items?: any[] };

      if (fetchRes.ok && !data.error) {
        activeKeyIndex = i;
        searchData = data;
        break;
      }

      if (isQuotaError(fetchRes.status, data)) {
        exhaustedKeyUntil[i] = now + KEY_EXHAUST_COOLDOWN_MS;
        if (i === activeKeyIndex) activeKeyIndex = Math.min(i + 1, apiKeys.length - 1);
      }

      if (!data.error?.message) continue;
      if (firstErrorStatus === 500) {
        firstErrorStatus = fetchRes.status || 500;
      }
    }

    if (!searchData) {
      const status = firstErrorStatus >= 400 && firstErrorStatus < 600 ? firstErrorStatus : 503;
      return res.status(status).json({ error: 'YouTube service unavailable, please try again later' });
    }

    const items = searchData.items ?? [];
    if (items.length === 0) {
      return res.status(404).json({ error: 'No video found' });
    }

    const ranked = items
      .map((item: any) => ({ item, score: scoreCandidate(item, title, artist) }))
      .filter((entry: { item: any; score: number }) => entry.score > -999)
      .sort((a: { score: number }, b: { score: number }) => b.score - a.score);

    const rankedTopicOnly = ranked.filter((entry: { item: any }) =>
      isTopicChannel(entry.item?.snippet?.channelTitle ?? '')
    );
    const bestTopic = rankedTopicOnly[0]?.item?.id?.videoId;
    const videoId = bestTopic ?? ranked[0]?.item?.id?.videoId ?? items[0]?.id?.videoId;

    if (!videoId) {
      return res.status(404).json({ error: 'No video found' });
    }

    return res.json({ videoId });
  } catch (error) {
    console.error('YouTube search route error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
};

